// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBowPe_aSC9Coqo5iA5LFyBk2j-_F80yV4',
    appId: '1:101220018288:web:97307960c1a7549a76ecb5',
    messagingSenderId: '101220018288',
    projectId: 'discreta-277d3',
    authDomain: 'discreta-277d3.firebaseapp.com',
    storageBucket: 'discreta-277d3.firebasestorage.app',
    measurementId: 'G-Y4RY83CP8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcVey8ZovirOreZLjyZXIgPS2Wm8wQJno',
    appId: '1:101220018288:android:2aa891da6a6f477676ecb5',
    messagingSenderId: '101220018288',
    projectId: 'discreta-277d3',
    storageBucket: 'discreta-277d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX1hwMrgzByiTWsUgkMD7Oux2YOHYzM1I',
    appId: '1:101220018288:ios:2951c015e6c5df9c76ecb5',
    messagingSenderId: '101220018288',
    projectId: 'discreta-277d3',
    storageBucket: 'discreta-277d3.firebasestorage.app',
    iosBundleId: 'com.example.discreta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX1hwMrgzByiTWsUgkMD7Oux2YOHYzM1I',
    appId: '1:101220018288:ios:2951c015e6c5df9c76ecb5',
    messagingSenderId: '101220018288',
    projectId: 'discreta-277d3',
    storageBucket: 'discreta-277d3.firebasestorage.app',
    iosBundleId: 'com.example.discreta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBowPe_aSC9Coqo5iA5LFyBk2j-_F80yV4',
    appId: '1:101220018288:web:ae7b15a4b744874976ecb5',
    messagingSenderId: '101220018288',
    projectId: 'discreta-277d3',
    authDomain: 'discreta-277d3.firebaseapp.com',
    storageBucket: 'discreta-277d3.firebasestorage.app',
    measurementId: 'G-M7C73152NE',
  );
}
