export const AUTH_ERROR_CODES = {
    MISSING_FIELDS: "MISSING_FIELDS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCESS_CODE_MAX_USES_OR_INVALID: "ACCESS_CODE_MAX_USES_OR_INVALID",
    SERVER_ERROR: "SERVER_ERROR",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
} as const;